
export default defineEventHandler(() => {
    return {
        code: 0,
        message: 'success',
        data: {
           list:[
            {
                name:'mfex-project',
                version:'https://img.shields.io/npm/v/mfex-project',
                download:'https://img.shields.io/npm/dt/mfex-project',
                link:'https://www.npmjs.com/package/mfex-project',
            },
            {
                name:'eslint-config-hfex',
                version:'https://img.shields.io/npm/v/eslint-config-hfex',
                download:'https://img.shields.io/npm/dt/eslint-config-hfex',
                link:'https://www.npmjs.com/package/eslint-config-hfex',
            },
            {
                name:'commitlint-config-hfex',
                version:'https://img.shields.io/npm/v/commitlint-config-hfex',
                download:'https://img.shields.io/npm/dt/commitlint-config-hfex',
                link:'https://www.npmjs.com/package/commitlint-config-hfex',
            },
            {
                name:'vue-pithy-calendar',
                version:'https://img.shields.io/npm/v/vue-pithy-calendar',
                download:'https://img.shields.io/npm/dt/vue-pithy-calendar',
                link:'https://www.npmjs.com/package/vue-pithy-calendar',
            },
            {
                name:'vue-pithy-rate',
                version:'https://img.shields.io/npm/v/vue-pithy-rate',
                download:'https://img.shields.io/npm/dt/vue-pithy-rate',
                link:'https://www.npmjs.com/package/vue-pithy-rate',
            },
            {
                name:'vue-pithy-pagination',
                version:'https://img.shields.io/npm/v/vue-pithy-pagination',
                download:'https://img.shields.io/npm/dt/vue-pithy-pagination',
                link:'https://www.npmjs.com/package/vue-pithy-pagination',
            },
            {
                name:'hfex-check',
                version:'https://img.shields.io/npm/v/hfex-check',
                download:'https://img.shields.io/npm/dt/hfex-check',
                link:'https://www.npmjs.com/package/hfex-check',
            },
            {
                name:'hfex-icon',
                version:'https://img.shields.io/npm/v/hfex-icon',
                download:'https://img.shields.io/npm/dt/hfex-icon',
                link:'https://www.npmjs.com/package/hfex-icon',
            },
            {
                name:'hfex-icon-plugin',
                version:'https://img.shields.io/npm/v/hfex-icon-plugin',
                download:'https://img.shields.io/npm/dt/hfex-icon-plugin',
                link:'https://www.npmjs.com/package/hfex-icon-plugin',
            },
            {
                name:'hfex-list',
                version:'https://img.shields.io/npm/v/hfex-list',
                download:'https://img.shields.io/npm/dt/hfex-list',
                link:'https://www.npmjs.com/package/hfex-list',
            },
            {
                name:'hfex-prettier-config',
                version:'https://img.shields.io/npm/v/hfex-prettier-config',
                download:'https://img.shields.io/npm/dt/hfex-prettier-config',
                link:'https://www.npmjs.com/package/hfex-prettier-config',
            },
            {
                name:'hfex-stylelint-config',
                version:'https://img.shields.io/npm/v/hfex-stylelint-config',
                download:'https://img.shields.io/npm/dt/hfex-stylelint-config',
                link:'https://www.npmjs.com/package/hfex-stylelint-config',
            },
            {
                name:'hhjvuemusic',
                version:'https://img.shields.io/npm/v/hhjvuemusic',
                download:'https://img.shields.io/npm/dt/hhjvuemusic',
                link:'https://www.npmjs.com/package/hhjvuemusic'
            }
           ]
          
        }
    }
})